### ISSUE TITLE
Prohibit to use atomicfu for public API (public & protected)

### ISSUE THREAD

**Issue by bashor** [Kotlin/kotlinx-atomicfu#119]
The ideal solution is providing custom checks for frontend. 
Harder to implement since it requires a new integration, but will provide the best DX -- early error, including inside IDE.

Acceptable solution -- report diagnostic from the backend.
Simpler to implement, but likely still requires to extend current API, anyway it's better than crash the compiler or a user application.

**Comment by mvicsokolova** [comment]
Currently, atomicfu compiler plugin only allows the usage of private and internal properties, please refer to the [README](https://github.com/Kotlin/kotlinx-atomicfu?tab=readme-ov-file#usage-constraints) for other usage constraints.
