### ISSUE TITLE
Let's strongly recommend avoid using atomicfu for public API (public & protected)

### ISSUE THREAD

**Issue by bashor** [Kotlin/kotlinx-atomicfu#120]
At least by changing this section:
https://github.com/kotlin/kotlinx.atomicfu#dos-and-donts 

The best solution is adding a check, see #119

**Comment by elizarov** [comment]
We do actually have a test in `kotlinx.coroutines` that makes sure no atomic even leaks outside of the module.

**Comment by mvicsokolova** [comment]
Here is the related issue: #119
