### ISSUE TITLE
Support Android Native targets

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx-atomicfu#122]
This is needed for https://github.com/Kotlin/kotlinx.coroutines/issues/812
See also https://github.com/Kotlin/kotlinx.coroutines/issues/1808

**Comment by elizarov** [comment]
This shoud be as easy as adding the following lines to [`atomicfu/build.gradle`](https://github.com/Kotlin/kotlinx.atomicfu/blob/master/atomicfu/build.gradle):
```
            addTarget(presets.androidNativeArm32)
            addTarget(presets.androidNativeArm64)
            addTarget(presets.androidNativeX86)
            addTarget(presets.androidNativeX64)
```
It builds successfully. But we need to test it somehow.

**Comment by piiertho** [comment]
Hi @elizarov !

I guess I will try to compile it and use it on my kotlin wrapper for Godot in a first time.
Then I'll see if I have an idea to make test and run them in CI.

You talked about infrastructure limitation to do the test, can you give some insight about those limitations ?

**Comment by elizarov** [comment]
We have not explored yet how to setup a test for the Android/Native code that is compiled that way. Propbably, it needed to be run under Android emulateor and we have not looked yet at how we can make it happen on our CI via Grable.

**Comment by piiertho** [comment]
> We have not explored yet how to setup a test for the Android/Native code that is compiled that way. Propbably, it needed to be run under Android emulateor and we have not looked yet at how we can make it happen on our CI via Grable.

That was my first thinking. I'll try it as soon as I d'une the time to do it :)

**Comment by natario1** [comment]
Is there any progress on this issue? Are you using your own internal CI? How can one contribute exactly?

**Comment by elizarov** [comment]
We don't have resources to work on it at the moment.

**Comment by glootjofo** [comment]
I think a lot of people want to help on this, but seeing your CI pipeline is closed, could you perhaps either make it possible for people to contribute to it, or just swap to github actions? There is a lot of will, but we can't help you guys, and it sucks.

**Comment by mvicsokolova** [comment]
We are working internally on guarantees that we are ready to provide for each individual target (as well as the overall understanding which targets we are going to support) and as soon as the public guarantees are published, we'll add each supported target to all our libraries at once
