### ISSUE TITLE
Common wrapper for native atomic APIs

### ISSUE THREAD

**Issue by saket** [Kotlin/kotlinx-atomicfu#135]
Not sure if it makes sense adding in this library, but have there been any discussions around adding common wrappers for atomic* functions (e.g., `atomicLazy`) that are only available on native?

**Comment by elizarov** [comment]
What would be the use-case? Why would you need it?

**Comment by saket** [comment]
I recently had to add a `atomicLazy()` wrapper to my common module that gets typealiased to native `atomicLazy()` so that I could call it from my common `object`. Here's the [commit](https://github.com/saket/press/commit/a259baa2b016cde302c848e34394c2e9506bf915) if it offers more context. 

Perhaps this request is similar to how [Stately](https://github.com/touchlab/Stately) offers common definitions for `freeze` et al so that they can be used from common code.
