### ISSUE TITLE
Support for WASM & linArm32

### ISSUE THREAD

**Issue by patjackson52** [Kotlin/kotlinx-atomicfu#142]
I believe the only platforms that are not currently supported are WASM & linArm32.  Are there plans to support these?  As a library author targeting all possible kotlin platforms it would be great if atomicFu could just be dropped into a shared module for all platforms.

**Comment by elizarov** [comment]
Currently, we lack the infrastructure to test `linuxArm32` targets. However, our long-term plan is to completely revamp the distribution model so that we don't have to build binaries for each target in the first place.

**Comment by slavonnet** [comment]
And SIMD!

**Comment by napperley** [comment]
@elizarov - How will testing be done without the binaries? With Kotlin Native all testing has to be done through executing a binary file, which has to be created beforehand.

**Comment by andreypfau** [comment]
@elizarov Any updates?

**Comment by mvicsokolova** [comment]
We are working internally on guarantees that we are ready to provide for each individual target (as well as the overall understanding which targets we are going to support) and as soon as the public guarantees are published, we'll add each supported target to all our libraries at once
