### ISSUE TITLE
[jvm] bug: variable not found when using public delegated property

### ISSUE THREAD

**Issue by ArcticLampyrid** [Kotlin/kotlinx-atomicfu#186]
My code: (`RpcChannel.service`)
ArcticLampyrid/KtJsonRpcPeer@e5559a8eec33aa28ab98efb64e836d561292353b (fixed by ArcticLampyrid/KtJsonRpcPeer@644a12afe9e14ae2fc8f6ec6220f6cbef950df08 via abandoning delegate)

Note that it works well when used in its own project, but when **other projects use it as a dependency**, error occurs.
[Example](https://github.com/UBotPlatform/KtUBotCommon/commit/b06dd85aa28634854571c31036499bc02111357a#diff-65e4220976f403059bce273ed98bab550fc1176e550f4f87d13ccfee0e34154eR160) / [Build log](https://jitpack.io/com/github/UBotPlatform/KtUBotCommon/0.6.2/build.log)
```
e: /home/jitpack/build/src/commonMain/kotlin/ubot/common/UBotClientHost.kt: (160, 17): Unresolved reference: service
e: /home/jitpack/build/src/commonMain/kotlin/ubot/common/UBotClientHost.kt: (189, 17): Unresolved reference: service
```

I don't test JVM IR backend.

**Comment by mvicsokolova** [comment]
Thank you for the report and sorry for the delayed answer.

I guess it is a bug in visibility modifiers for fields generated during transformation of delegated properties.

**Comment by Lukellmann** [comment]
I also came across this and it doesn't seem to be a problem with the generated visibility modifiers but instead a missing entry in the generated `@kotlin.Metadata` annotation. I'm able to access getters and setters from java just fine.

**Comment by Lukellmann** [comment]
JVM IR transformation doesn't seem to have this issue.

**Comment by mvicsokolova** [comment]
I can not reproduce this issue anymore with the latest version of JVM IR transformation provided in `0.23.0` atomicfu release. If any further problems arise, feel free to reopen this issue.
