### ISSUE TITLE
Gradle JVM plugiin: transformAtomicfuClasses implicit dependency between subprojects

### ISSUE THREAD

**Issue by svilen-ivanov** [Kotlin/kotlinx-atomicfu#191]
I have 2 subprojects which both use Atomic FU and one of them depend on another (`inmem` depends on `core` from the example below)

I receive the following warning when I enable Atomicfu Gradle plugin

```
> Task :inmem:transformAtomicfuClasses
Execution optimizations have been disabled for task ':inmem:transformAtomicfuClasses' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '[PROJECT DIR]/build/classes/atomicfu/main'. Reason: Task ':inmem:transformAtomicfuClasses' uses this output of task ':core:transformAtomicfuClasses' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

I'm using AdoptJDK 16 and Gradle 7.0.2

Is there a way to make the dependency explicit? I can work on minimal reproducible build.

**Comment by mvicsokolova** [comment]
Please migrate to the JVM IR transformations, refer to the [README](https://github.com/Kotlin/kotlinx-atomicfu?tab=readme-ov-file#atomicfu-compiler-plugin) for more details.
