### ISSUE TITLE
Support linuxarm32hfp target

### ISSUE THREAD

**Issue by arkivanov** [Kotlin/kotlinx-atomicfu#207]
The lack of `linuxarm32hfp` target prevents AtomicFU from being used in Reaktive. And I think the same story for coroutines.

PS: Looks like there is a PR available #193, but it did not receive any attention.

**Comment by mvicsokolova** [comment]
Please, see the same issue #193

**Comment by lppedd** [comment]
@mvicsokolova consider reopening this and adding `linuxArm32Hfp`, as other libraries like `kotlinx-serialization` did, since the target is just deprecated, but not removed.

See https://github.com/Kotlin/kotlinx.serialization/pull/2505
