### ISSUE TITLE
document non-root project behavior for `org.jetbrains.kotlinx:atomicfu-gradle-plugin`

### ISSUE THREAD

**Issue by anatawa12** [Kotlin/kotlinx-atomicfu#210]
According to the code below, if the `org.jetbrains.kotlinx:atomicfu-gradle-plugin` dependency is declared on a non-root project,  'kotlinx-atomicfu' Gradle Plugin can't detect the version of `atomicfu-gradle-plugin` and it doesn't add dependency automatically.

https://github.com/Kotlin/kotlinx.atomicfu/blob/de4e55674c51f58cbc1f16b097d68c4ba42a5e7b/atomicfu-gradle-plugin/src/main/kotlin/kotlinx/atomicfu/plugin/gradle/AtomicFUGradlePlugin.kt#L30

Can you document this behavior?

**Comment by dimsuz** [comment]
Oh, so that's why I'm getting an "unresolved reference androidfu", after applying it to a non-root project. Not obvious at all, should be documented indeed. But it really shouldn't depend on being added to a root project, this breaks modularization.

**Comment by tadfisher** [comment]
A workaround is to add the plugin in `settings.gradle{.kts}` (in the `pluginManagement` block, for Gradle 7.+, with `apply false`) or in the root project's `plugins` block with `apply false`. Then it is added to the buildscript classpath without being applied to the root project.

**Comment by Lukellmann** [comment]
Another option would be including a file with the current version in the plugin jar, see https://discuss.gradle.org/t/how-can-a-custom-gradle-plugin-determine-its-own-version/36761

**Comment by mvicsokolova** [comment]
This issue will be fixed in the next release with these changes: #405

Now the version of the library is stored in the specified file, packed in the `atomicfu-gradle-plugin.jar`, and `AtomicfuGradlePlugin` gets the version of the applied plugin from this file, not from the root buildscript.
