### ISSUE TITLE
NoSuchMethodError kotlinx.atomicfu.AtomicRef <fqn>.access$get<property>$p

### ISSUE THREAD

**Issue by eygraber** [Kotlin/kotlinx-atomicfu#227]
I started getting the following error in one of my projects:

```
java.lang.NoSuchMethodError: 'kotlinx.atomicfu.AtomicRef com.eygraber.portal.internal.PortalEntryBuilder.access$get_postTransactionOps$p(com.eygraber.portal.internal.PortalEntryBuilder)'
```

This can be reprod by using https://github.com/eygraber/portal and running:

```
./gradle :samples:kotlin-inject:run
```

Then clicking the alarm icon in the middle of the screen, and then pressing the back button in the top left.

**Comment by mvicsokolova** [comment]
The error is not reproduced with atomicfu `0.18.4`
