### ISSUE TITLE
Autoconfig of Dependency brocken in kotlin 1.7.0

### ISSUE THREAD

**Issue by JochenGuckSnk** [Kotlin/kotlinx-atomicfu#232]
Hallo AtomicFu team,

I'm using AtomicFu in a multi platform; multi project setup. It looks similar to the Example project:
[FuExample.zip](https://github.com/Kotlin/kotlinx.atomicfu/files/8869647/FuExample.zip)
On kotlin version 1.6.20 every thing works.
On kotlin version 1.7.0 the build fails with : No matching variant of org.jetbrains.kotlin:atomicfu:1.7.0 was found.

**Comment by Zxilly** [comment]
Same error, hope for a workaround.

**Comment by Tapchicoma** [comment]
Following hacky workaround should work:
```kt
dependencies {
	components {
		withModule("org.jetbrains.kotlin:atomicfu") {
			withVariant("runtimeElements") {
				val runtimeElementsVariant = this
				this@withModule.addVariant("runtimeJsIrElements") {
					attributes.attribute(
						org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.attribute,
						org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType.js
					)
					attributes.attribute(
						org.jetbrains.kotlin.gradle.targets.js.KotlinJsCompilerAttribute.jsCompilerAttribute,
						org.jetbrains.kotlin.gradle.targets.js.KotlinJsCompilerAttribute.ir
					)
					attributes.attribute(Usage.USAGE_ATTRIBUTE, project.objects.named(Usage.JAVA_RUNTIME))
					runtimeElementsVariant.withFiles {
						val runtimeElementsFiles = this as org.gradle.api.internal.artifacts.repositories.resolver.DefaultMutableVariantFilesMetadata
						this@addVariant.withFiles {
							runtimeElementsFiles.files.forEach {
								addFile(it.name)
							}
						}
					}
				}
			}
		}
	}
}
```

**Comment by mvicsokolova** [comment]
This problem with unresolved dependencies was [fixed](https://github.com/JetBrains/kotlin/commit/d015b2b899cf42b447186bfe9c2583f07254ae1c) in Kotlin `1.7.10` via correct publishing of compiler plugin runtime module and [supported](https://github.com/Kotlin/kotlinx-atomicfu/commit/8f500b2c20abc2c614ad7d3d01bf5430f987f68c) since kotlinx.atomicfu `0.18.2`.

The similar issue: #234
