### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:atomicfu:1.7.0.

### ISSUE THREAD

**Issue by danny-su** [Kotlin/kotlinx-atomicfu#234]
Could not determine the dependencies of task ':data:jsPackageJson'.
> Could not resolve all dependencies for configuration ':data:jsNpm'.
   > Could not resolve org.jetbrains.kotlin:atomicfu:1.7.0.
     Required by:
         project :data
      > No matching variant of org.jetbrains.kotlin:atomicfu:1.7.0 was found. The consumer was configured to find a usage of 'kotlin-runtime' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:
          - Variant 'apiElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a library, preferably optimized for standard JVMs:
              - Incompatible because this component declares an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
          - Variant 'gradle70ApiElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a library, preferably optimized for standard JVMs:
              - Incompatible because this component declares an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
          - Variant 'gradle70JavadocElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a runtime of a component:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'js')
          - Variant 'gradle70RuntimeElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a runtime of a library, preferably optimized for standard JVMs:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
          - Variant 'gradle70SourcesElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a runtime of a component:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'js')
          - Variant 'javadocElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a runtime of a component:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'js')
          - Variant 'runtimeElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a runtime of a library, preferably optimized for standard JVMs:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
          - Variant 'sourcesElements' capability org.jetbrains.kotlin:atomicfu:1.7.0 declares a runtime of a component:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
                  - Doesn't say anything about org.jetbrains.kotlin.js.compiler (required 'ir')
                  - Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'js')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by mvicsokolova** [comment]
This problem with unresolved dependencies was [fixed](https://github.com/JetBrains/kotlin/commit/d015b2b899cf42b447186bfe9c2583f07254ae1c) in Kotlin `1.7.10` via correct publishing of compiler plugin runtime module and [supported](https://github.com/Kotlin/kotlinx-atomicfu/commit/8f500b2c20abc2c614ad7d3d01bf5430f987f68c) since kotlinx.atomicfu `0.18.2`.
