### ISSUE TITLE
Value classes don't work on native

### ISSUE THREAD

**Issue by DRSchlaubi** [Kotlin/kotlinx-atomicfu#291]
Currently this update call never finishes

```kotlin
public value class Value(public val value: Int)

public fun main() {
    val atomic = atomic(Value(1))
    println(atomic)
    atomic.update { Value(2) }
    println(atomic)
}
```

Might be fixed by #261

**Comment by mvicsokolova** [comment]
Furthermore, please note that the atomicfu plugin can only perform transformations of atomic values declared as properties. It won't be able to perform transformations on atomic values declared as local variables. For example, the code below is correct:

```
private val atomic = atomic(1)

public fun main() {
    println(atomic)
    atomic.update { 2 }
    println(atomic)
}
```

**Comment by DRSchlaubi** [comment]
How is this not a bug?

**Comment by DRSchlaubi** [comment]
If the plugin does not support this behavior it should at least fail at compile time instead of causing a deadlock at runtime

**Comment by mvicsokolova** [comment]
This behaviour will be prohibited in the compiler plugin: [KT-61584](https://youtrack.jetbrains.com/issue/KT-61584/atomicfu-prohibit-declaration-of-AtomicReference-to-the-value-class-in-the-compiler-plugin)
