### ISSUE TITLE
Is there a way to add dependency only for tests?

### ISSUE THREAD

**Issue by Andrew0000** [Kotlin/kotlinx-atomicfu#321]
Is it possible to add kotlinx-atomicfu dependency only for test module?
For instance like this:
```
testImplementation("org.jetbrains.kotlinx:atomicfu...")
```
or in case of multiplatform:
```
val commonTest by getting {
  dependencies {
      implementation("org.jetbrains.kotlinx:atomicfu...")
  }
}
```

**Comment by mvicsokolova** [comment]
It is possible to only add atomicfu dependency to tests via
```
dependencies {
  testImplementation("org.jetbrains.kotlinx:atomicfu:0.21.0")
}
```
This way you just add a compile and runtime dependency to the atomicfu library and no transformations are performed.

It is not possible to enable transformations for tests only though.
