### ISSUE TITLE
Get rid of the deprecated Visitor API in MetadataTransformer

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-atomicfu#328]
This migration is not critical, because MetadataTransformer is part of the legacy bytecode transformer that will soon be completely replaced with the JVM IR transformation.

**Comment by mvicsokolova** [comment]
JVM bytecode transformer is going to be deprecated and removed, so this is a low priority issue, most probably it's not going to be done: #338

**Comment by fzhinkin** [comment]
Duplicates #439, fixed in https://github.com/Kotlin/kotlinx-atomicfu/pull/441
