### ISSUE TITLE
Replace @Suppress with @AllowDifferentMembersInActual once updated to 1.9.20

### ISSUE THREAD

**Issue by nikitabobko** [Kotlin/kotlinx-atomicfu#333]
Replace the following suppressions:
```
@Suppress("ACTUAL_CLASSIFIER_MUST_HAVE_THE_SAME_MEMBERS_AS_NON_FINAL_EXPECT_CLASSIFIER")
@Suppress("NON_ACTUAL_MEMBER_DECLARED_IN_EXPECT_NON_FINAL_CLASSIFIER_ACTUALIZATION")
```
with `@AllowDifferentMembersInActual`

Note: feel free to convert this issue to "1.9.20 update tracking issue"

**Comment by mvicsokolova** [comment]
`AllowDifferentMembersInActual` was removed for 1.9.20 for all targets.
