### ISSUE TITLE
`AtomicRef<Int>.compareAndSet` always fails when `value >= 128` on macOS and iOS

### ISSUE THREAD

**Issue by paxbun** [Kotlin/kotlinx-atomicfu#369]
I'm using kotlinx-atomicfu 0.22.0. I was having a problem where my program halts at `AtomicRef<Int>.getAndUpdate`, and I found that `AtomicRef<Int>.compareAndSet` always fails when the value >= 128 on macOS and iOS, both for JVM and native. For example:

```kotlin
for (i in 0 until 1024) {
    val a = kotlinx.atomicfu.atomic<Int>(i)
    print("${i}: ${a.compareAndSet(i, 8192)}")
}
```
run result:
```
0 true
...
127 true
128 false
...
1023 false
```

This does not happen when I use `AtomicInt` instead of `AtomicRef<Int>`.

```kotlin
for (i in 0 until 1024) {
    val a = kotlinx.atomicfu.atomic(i)
    println("${i}: ${a.compareAndSet(i, 8192)}")
}
```
run result:
```
0 true
...
127 true
128 true
...
1023 true
```

**Comment by paxbun** [comment]
This is the original issue: https://gitlab.com/trixnity/uniffi-kotlin-multiplatform-bindings/-/issues/24

**Comment by paxbun** [comment]
Found that `kotlin.concurrent.AtomicReference<Int>` (not kotlinx) has the same problem. Create a fresh multiplatform project, set the Kotlin version to 1.9.20, run the following, and you'll get the same result.
```kotlin
import kotlin.concurrent.AtomicReference

fun main() {
    repeat(129) {
        val a = AtomicReference(it)
        val result = a.compareAndSet(it, 8192)
        println("$it: $result")
    }
}
```

**Comment by paxbun** [comment]
Is it an expected behavior and an imitation of JVM's Integer pooling? I also found that `compareAndSet` always fails when `value < -128`.

**Comment by qwwdfsad** [comment]
It seems like we need a proper inspection or compiler diagnostic here.
`AtomicRef<Int>` is as dangerous and tricky as Java's `AtomicReference<Integer>` -- it leaks the fact that boxed integer values may or may not be cached, and atomic ref (rightfully) uses identity equals and fails here.

So I'd say the behaviour is as intended, but we need a proper diagnostic to prevent such a bug (note: it's also reproducible with other primitives including booleans)

**Comment by qwwdfsad** [comment]
Posted the solution internally, re-posting here:
```
public fun <T> atomic(initial: T): AtomicRef<T> = atomic(initial, TraceBase.None)
public fun atomic(initial: Int): AtomicInt = atomic(initial, TraceBase.None)
@JvmName("atomicInt")
@Suppress("FINAL_UPPER_BOUND")
public fun <T : Int> atomic(initial: T): AtomicInt = atomic(initial.toInt(), TraceBase.None)

private val atomic = atomic<Int>(0)

@Test
fun foo() {
    atomic.value = 129
    println(atomic.compareAndSet(129, 130))
}
```

**Comment by mvicsokolova** [comment]
As we're about to introduce common Atomic types in stdlib, I suggest to rephrase this task to adding a compiler diagnostic which warns about the error prone usage of `kotlin.concurrent.AtomicRef<Int>`.

I've filed an issue here: https://youtrack.jetbrains.com/issue/KT-73508/Add-a-warning-diagnostic-for-using-kotlin.concurrent.AtomicRefInt
