### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference

### ISSUE THREAD

**Issue by yangwuan55** [Kotlin/kotlinx-atomicfu#371]
look here for detail:
https://github.com/Kotlin/kotlinx.coroutines/issues/3820

Like a kotlinx-atomicfu bug on android platform.

**Comment by qwwdfsad** [comment]
It's not un atomicfu bug as explained here: https://github.com/Kotlin/kotlinx.coroutines/issues/3820#issuecomment-1714272221
