### ISSUE TITLE
Duplicate library name warning with atomicfu 0.23.0

### ISSUE THREAD

**Issue by eygraber** [Kotlin/kotlinx-atomicfu#382]
This issue picks up where https://github.com/Kotlin/kotlinx-atomicfu/issues/289 left off.

When I run `portal:compileTestKotlinJs` on [my project](https://github.com/eygraber/portal) I get the following warning (really error since I have `-Werror`):

```
w: duplicate library name: com.eygraber:portal
```

That library doesn't reference itself in any way, and using `git bisect` I found that this started happening when updating atomicfu from 0.21.0 to 0.22.2

That project is using coroutines 1.8.0-RC

**Comment by eygraber** [comment]
Any sense on when this can be resolved?

**Comment by lppedd** [comment]
Is this the same issue? https://youtrack.jetbrains.com/issue/KT-62653/

**Comment by lppedd** [comment]
@eygraber I recalled that one and this comment
https://youtrack.jetbrains.com/issue/KT-51110/Pseudo-circular-dependency-causes-duplicate-library-name-warning-for-JS-target#focus=Comments-27-7656620.0-0

**Comment by eygraber** [comment]
It could be KT-51110 but then that would indicate that atomicfu is messing around with the compilations incorrectly, because my module doesn't depend on anything that depends on it. 

Additionally as I stated above

> using git bisect I found that this started happening when updating atomicfu from 0.21.0 to 0.22.2

**Comment by mvicsokolova** [comment]
@eygraber, hi! Do you still face this issue after update to atomicfu `0.23.2`?

I could not see the `duplicate library name` warning while building your [portal](https://github.com/eygraber/portal) project from master branch.

**Comment by eygraber** [comment]
Issue is fixed, than you!

**Comment by eygraber** [comment]
Not sure if this is a new issue or not, but I'm seeing this error again in that project - https://github.com/eygraber/portal/actions/runs/9055078137/job/24875658117
