### ISSUE TITLE
After applying atomicfu plugin to a project with Java sources corresponding classes are missing

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/kotlinx-atomicfu#388]
Based on https://github.com/Kotlin/kotlinx-atomicfu/issues/384#issuecomment-1869007976

If a project contains both Kotlin and Java sources, application of the `atomicfu` plugin leads to Java classes being lost.

Here's a reproducer: https://github.com/fzhinkin/atomicfu-issues-with-java-sources

Everything works fine with atomicfu version below `0.21.0`.

**Comment by mvicsokolova** [comment]
Thank you for the reproducer 🙏🏻
