### ISSUE TITLE
JVM transformation: unsupported branching/control for not-null assertion

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx-atomicfu#39]
```kotlin
class Example {
    private val a = atomic<Any?>(null)
    private val something: Any? = "here it is"

    fun f() {
        a.compareAndSet(something!!, null)
    }
```

```
Example::f: Unsupported branching/control within atomic operation
Example::f: standalone invocation of kotlinx.atomicfu.AtomicRef::compareAndSet that was not traced to previous field load
```

Workarounds:
- remove `!!` assertion
- extract expected value into a new variable (but keep `!!` assertion)

Version: 0.11.10-eap13
Kotlin: 1.3.0-rc-131

**Comment by DRSchlaubi** [comment]
Updating to KT 1.6 brought this issue back
```
standalone invocation of kotlinx.atomicfu.AtomicRef::compareAndSet that was not traced to previous field load
```

when using AtomicRef.update

**Comment by fzhinkin** [comment]
Taking my words back: with a reproducer from https://github.com/Kotlin/kotlinx-atomicfu/issues/180 it's possible to get `standalone invocation of kotlinx.atomicfu.AtomicBoolean::compareAndSet that was not traced to previous field load` with Kotlin `2.1.0-RC2` and AFU `0.26.0`:
```kotlin
val atomicBool = atomic(false)

fun main() {
    on {
        atomicBool.update { true }
    }
}

fun on(block: suspend () -> Unit) {
    GlobalScope.launch {
        block()
    }
}
```
