### ISSUE TITLE
ReentrantLock errors in native source set with Kotlin 2.0.0-Beta3

### ISSUE THREAD

**Issue by eygraber** [Kotlin/kotlinx-atomicfu#401]
I am using a `ReentrantLock` in a native source set from atomicfu 0.23.2:

```kotlin
private val lock = ReentrantLock()

fun <T> get(key: String, init: () -> T): T {
        return lock.withLock {
            init()
        }
}
```

which works fine on Kotlin 1.9.20, but I get the following errors with Kotlin 2.0.0-Beta3:

```
Expected class 'expect class ReentrantLock : Any' does not have default constructor.

Overload resolution ambiguity between candidates: [fun <T> ReentrantLock.withLock(block: () -> T): T, expect fun <T> ReentrantLock.withLock(block: () -> T): T]
```

If I replace it with:

```kotlin
private val lock = SynchronizedObject()
```

then it works fine.

**Comment by eygraber** [comment]
Happens in Beta4 as well.

**Comment by mvicsokolova** [comment]
Thank you for the report! Actually, that's a bug in the ReentrantLock implementation and it's reproduced with earlier versions of Kotlin as well. 

Also, you can use a factory function instead of calling the constructor directly: 

```kotlin
private val lock = reentrantLock()
```

**Comment by eygraber** [comment]
Thank you, using the factory function worked.
