### ISSUE TITLE
Tidy up our build setup

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx-atomicfu#402]
Follow up of https://youtrack.jetbrains.com/issue/QA-1118/

* [x] Migrate from Groovy to Kotlin DSL everywhere
* [x] Get rid of kludges and workarounds for old KMP, namely `Idea.isActive` and dynamic sourcesets hackery
* [x] Migrate to newer features of KMP, namely default source sets hierarchy 
* [ ] https://youtrack.jetbrains.com/issue/KT-65886/
* [ ] https://youtrack.jetbrains.com/issue/KT-65884/

**Comment by mvicsokolova** [comment]
Some tasks related to cleaning up the build sripts are tracked here: https://github.com/Kotlin/kotlinx-atomicfu/issues/421

**Comment by mvicsokolova** [comment]
All these problems were resolved within this task: #421
