### ISSUE TITLE
atomicfu-gradle-plugin does not configure dependencies, when it applied in a non-root build sript.

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-atomicfu#403]
There is a bug in resolution of `atomicfu-gradle-plugin` version, when atomicfu plugin is applied in the build script of the module, and not in the rootProject. In this case atomicfu does not configure necessary dependencies:  `compileOnly` library dependency for commonMain and `implementation` dependency for commonTest sourceSet, thus causing compilation errors.

**Comment by lukellmann** [comment]
Will this fix #210 too?
