### ISSUE TITLE
Deprecate minusAssign/plusAssign operators from public API

### ISSUE THREAD

**Issue by mvicsokolova** [Kotlin/kotlinx-atomicfu#416]
I suggest to remove `minusAssign`/`plusAssign` operators from public API of `AtomicInt` and `AtomicLong`. 

- these operators are not consistent with the API of Java atomics, K/N atomics and it's better to use `addAndGet` instead.
- this API is not widely used (though I should check that properly)
- these operators were added just because they seemed useful

Not the reasons to remove the API, but related problems: 
- this API is not supported by the compiler plugin and causes problems like this: #274
-  also it is not covered by tests

Alternative solution is to solve the problems above and keep the API.
And of course it's more convenient to write: 

```
private val x = atomic(0)

x -= 5
```
vs
```
private val x = atomic(0)

x.addAndGet(-5)
```

@fzhinkin WDYT? 👀

**Comment by lppedd** [comment]
IMO the operator functions feel more natural. And I can swap an atomic with a normal number type (and vice-versa) without changes.

People working with Kotlin should be aware of operator functions, and the IDE provides navigation to the target in case one wants to explore the code.

**Comment by mvicsokolova** [comment]
That's a good point, right.

**Comment by mvicsokolova** [comment]
These operators will be supported in the atomicfu compiler plugin for the future Kotlin versions: [KT-67839 ](https://youtrack.jetbrains.com/issue/KT-67839/Atomicfu-plugin-support-transformation-of-minusAssign-plusAssign-operators)
