### ISSUE TITLE
SynchronizedObject for kotlin/native

### ISSUE THREAD

**Issue by asdshuaishuai** [Kotlin/kotlinx-atomicfu#437]
Hello, I am currently using Kotlin to attempt to rewrite the JDBC standard API library, but I have encountered some issues. In the DriverManager object class, I need to ensure that its internal methods are synchronized. In Kotlin/JVM and Kotlin/JS, I can try to use `synchronized` to ensure this, but there is no `synchronized` modifier in Kotlin/Native. Therefore, I hope to find some inspiration from AtomicFu, but I found that `SynchronizedObject` only mentions Kotlin/JVM and Kotlin/JS. Is there any implementation related to Kotlin/Native?

**Comment by vbarthel-fr** [comment]
Hello! I'm not a contributor of this library, nor very knowledgeable on this topic, but I guess you can achieve such construction using a `kotlinx.atomicfu.locks.ReentrantLock` (available in Kotlin/Native - I have been using it successfully on iOS) 

```kotlin
val lock = ReentrantLock()

fun someSynchronizedFunction() {
    lock.withLock {
        // Do some synchronized work
    }
}
```

More details in the "locks" section of the readme https://github.com/Kotlin/kotlinx-atomicfu?tab=readme-ov-file#locks

(Especially the recommandation of _not_ using this experimental package in other libraries whose other projects depend on)

> Note that package kotlinx.atomicfu.locks is experimental explicitly even while atomicfu is experimental itself, meaning that no ABI guarantees are provided whatsoever. API from this package is not recommended to use in libraries that other projects depend on.

**Comment by asdshuaishuai** [comment]
thinks
