### ISSUE TITLE
Question: Why the plugin is needed?

### ISSUE THREAD

**Issue by Andrew0000** [Kotlin/kotlinx-atomicfu#474]
I am an average programmer. This library is vague to me. Let me explain my thoughts and needs: 

I just need to write some thread-safe code (sometimes without suspend modifiers, this is why Mutex is out of question). So I need an analogue of AtomicInt / Volatile / synchronized from Java.

Why do I need some plugin for this simple task? 
What is the compile time overhead of the plugin? 
Is plugin replaceable with expect/actual on your side?

**Comment by fzhinkin** [comment]
Hey @Andrew0000! Thank you for the feedback. Indeed, the documentation could be improved to better describe the place and the role of the plugin.

In case you're still searching answers for the listed questions:

> So I need an analogue of AtomicInt / Volatile / synchronized from Java.

- There's already a [Volatile](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.concurrent/-volatile/) in the standard library.
- Boxed atomics are also available on JVM and Native, the work on providing common boxed atomic classes is currently in progress: https://youtrack.jetbrains.com/issue/KT-62423
- However, there's indeed no `synchronized` available across all the targets.

> Why do I need some plugin for this simple task?

Library's description claims that it _provides the idiomatic and efficient way of using atomic operations_. To some extent, both could be achieved without a plugin. On JVM, for instance, efficiency may imply using primitive volatile fields in conjunction with AF-updaters or var handles. These APIs works well, but they are anything but handy. The plugin makes all the heavy-lifting on developer's behalf here, so one can use atomicfu atomics as if they are plain old boxed atomics, but the resulting code is much more efficient.

> What is the compile time overhead of the plugin?

There is some overhead, and if you believe that it could be a problem for your project, there's no better way to check it other than applying the plugin to a project and measuring how it affects compilation.

> Is plugin replaceable with expect/actual on your side?

Besides the plugin, there's an atomicfu runtime library, that is fact provides set of expects/actuals. However, it does not replace the plugin which replaces boxed atomic classes with "inline" atomics.

**Comment by Andrew0000** [comment]
@fzhinkin thank a lot. So the plugin is an optimisation.


> There's already a [Volatile](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.concurrent/-volatile/) in the standard library.
> Boxed atomics are also available on JVM and Native, the work on providing common boxed atomic classes is currently in progress: https://youtrack.jetbrains.com/issue/KT-62423

Do I understand correctly that at the moment Volatile and AtomicInt (AtomicWhatever) don't work in commonMain?
Because the reason of my question is that I'm trying to understand what to use in commonMain for thread safety (besides Mutex, of course).

**Comment by Andrew0000** [comment]
> Besides the plugin, there's an atomicfu runtime library, that is fact provides set of expects/actuals

Maybe I'm a little blind, but I didn't find this in the repository description. So, can I just add this `api("org.jetbrains.kotlinx:atomicfu:0.25.0")` to my commonMain and use it? No pitfalls?

**Comment by fzhinkin** [comment]
> Do I understand correctly that at the moment Volatile and AtomicInt (AtomicWhatever) don't work in commonMain?

`Volatile` does work in commonMain, `AtomicInt` does not.

> Maybe I'm a little blind, but I didn't find this in the repository description. So, can I just add this `api("org.jetbrains.kotlinx:atomicfu:0.25.0")` to my commonMain and use it? Without the plugin. No pitfalls?

`imlpementation("org.jetbrains.kotlinx:atomicfu:0.25.0")`, but yes, it'll work without the plugin.

The main pitfalls are:
- it's not the intended way to use `atomicfu`, so there are no guarantees regarding the future of the artifact;
- performance will be a bit worse compared to what could be achieved with the plugin (but that might not be a concern);
- the plugin restricts how atomics could be used (for example, it does not allow public atomic properties as well as functions accepting or returning atomics), without the plugin these restrictions could be violated. If you'll decide to turn on the plugin at some point, your code might require some changes.
