### ISSUE TITLE
Disable JDK compatibility tests in kotlin-community/dev branch

### ISSUE THREAD

**Issue by fzhinkin** [Kotlin/kotlinx-atomicfu#488]
`kotlin-community/dev` is tested in different CI environment compared to what we do for AFU in general. Such environment does not allow installing arbitrary JDK versions using toolchain provisioning plugin. As a result, JDK-compat tests may fail.

We should disable affected tests in `kotlin-community/dev`.

**Comment by fzhinkin** [comment]
Mirrors KTI-1966

**Comment by mvicsokolova** [comment]
Thank you! The fix was merged to `kotlin-community/dev`.
