### ISSUE TITLE
Atomicfu plugin adds common dependencies to platform modules

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx-atomicfu#72]
Adding common dependency to a native module causes Gradle plugin to complain about it for **every** module. In ktor, it generates a huge number of warnings so one wouldn't be able to discover actual problems.

```
A compileOnly dependency is used in the Kotlin/Native target 'linuxX64':
Compilation: main

Dependencies:
org.jetbrains.kotlinx:atomicfu-common:0.12.9

Such dependencies are not applicable for Kotlin/Native, consider changing the dependency type to 'implementation' or 'api'.
```

**Comment by cy6erGn0m** [comment]
A possible solution is to not add these dependencies or stop using `compileOnly` and switch to `api` or `implementation`.

**Comment by mvicsokolova** [comment]
Related changes: #395
