### ISSUE TITLE
Support delegation properties

### ISSUE THREAD

**Issue by HKhademian** [Kotlin/kotlinx-atomicfu#83]
As atomic document says to leak atomic values to public use:

```kotlin
val _pref = atomic(0L)
var pref : Long
    get() = _pref.value
    set(value) { _pref.value = value }
```

so I think it's possible to have something like:

```kotlin
val pref by atomicVar(0L)
val pref by atomicVal(0L)

this::pref.atomic.value = 10
```

**Comment by elizarov** [comment]
It is indeed possible, but this is not efficient as of the moment. See https://youtrack.jetbrains.com/issue/KT-17034 and related issues for more details. Atmoics are not designed for general-purpose use. They are designed for use in low-level high-performance code, so it does not really make sense to provide a non-efficient way to work with them.

**Comment by mvicsokolova** [comment]
Delegated properties are currently supported by the library, please refer to the [README](https://github.com/Kotlin/kotlinx-atomicfu?tab=readme-ov-file#atomic-delegates) for more details.
